### ISSUE TITLE
Jose's Redirections

### ISSUE THREAD

**Issue by Pechyvo** [Db1zz/minishell#1]
- In redirection exits **<ins>WHOLE</ins>** minishell after its execution:
[rd_in_result.txt](https://github.com/user-attachments/files/17965900/rd_in_result.txt)

- Out redirection doesn't work as expected:
[rd_out_received.txt](https://github.com/user-attachments/files/17965892/rd_out_received.txt)
[rd_out_expected.txt](https://github.com/user-attachments/files/17965894/rd_out_expected.txt)

-  Out redirection needs <ins>0644</ins> flag as 3rd parameter when opening files to fix permission issues:
[redirection_perm_fix.txt](https://github.com/user-attachments/files/17965912/redirection_perm_fix.txt)

**Comment by Db1zz** [comment]
Fixed, thank you ;)
